export const AUTH_ACTION_TYPES = {
	SET_AUTH_TOKEN: 'auth/SET_AUTH_TOKEN',
	SET_CURRENT_USER_START: 'auth/SET_CURRENT_USER_START',
	SET_CURRENT_USER_SUCCESS: 'auth/SET_CURRENT_USER_SUCCESS',
	SET_CURRENT_USER_FAIL: 'auth/SET_CURRENT_USER_FAIL',
	RESET_TO_INITIAL_STATE: 'auth/RESET_TO_INITIAL_STATE',
};
