export const SANTA_EVENT_ACTION_TYPES = {
	SET_EVENT_DETAILS: 'santaEvent/SET_EVENT_DETAILS',
	SET_GROUP_DETAILS: 'santaEvent/SET_GROUP_DETAILS',
	SET_MEMBER_COUNT: 'santaEvent/SET_MEMBER_COUNT',
	SET_MEMBER_DATA: 'santaEvent/SET_MEMBER_DATA',
	SET_SHUFFLED_MEMBER_DATA: 'santaEvent/SET_SHUFFLED_MEMBER_DATA',
	SET_PAIRS_DETAILS: 'santaEvent/SET_PAIRS_DETAILS',
	PERSIST_DATA_START: 'santaEvent/PERSIST_DATA_START',
	PERSIST_DATA_FAIL: 'santaEvent/PERSIST_DATA_FAIL',
	PERSIST_DATA_SUCCESS: 'santaEvent/PERSIST_DATA_SUCCESS',
	RESET_TO_INITIAL_STATE: 'santaEvent/RESET_TO_INITIAL_STATE',
};
