export const WISHLIST_ACTION_TYPES = {
	SET_WISHLIST: 'wishlist/SET_WISHLIST',
	SET_WISH: 'wishlist/SET_WISH',
	DATA_TRANSFER_START: 'wishlist/DATA_TRANSFER_START',
	DATA_TRANSFER_FAIL: 'wishlist/DATA_TRANSFER_FAIL',
	DATA_TRANSFER_SUCCESS: 'wishlist/DATA_TRANSFER_SUCCESS',
};
